# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.json', '.'),
        ('printer_*.py', '.'),
        ('printer_config.py', '.'),
        ('printer_utils.py', '.'),
        ('cloud_*.py', '.'),
        ('edge_node_info.py', '.'),
    ],
    hiddenimports=[
        'gradio',
        'pandas',
        'zeroconf',
        'requests',
        'pywin32',
        'win32api',
        'win32print',
        'PIL',
        'PyPDF2',
        'platform',
        'threading',
        'tempfile',
        'time',
        'os',
        'psutil',
        'websockets',
        'asyncio',
        'json',
        'jwt',
        'logging'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='FlyPrint',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)